local m = {}

m.ID = "id"
m.CharacterType = "characterType"
m.Race = "race"
m.Sex = "sex"
m.MagicType = "magicType"
m.Language = "language"
m.LastSpokenText = "lastSpokenText"
m.CurrentLoginTimestamp = "currentLoginTimestamp"
m.TotalOnlineTime = "totalOnlineTime"
m.LastActionScript = "lastActionScript"
m.LastActionFunction = "lastActionFunction"
m.LastActionArgs = "lastActionArgs"
m.NPC = "npc"
m.Monster = "monster"
m.MonsterSpawn = "monsterSpawn"
m.NextRandomMoveTick = "nextRandomMoveTick"
m.Script = "script"
m.Dead = "dead"
m.Data = "data"
m.Content = "content"
m.Count = "count"
m.Quality = "quality"
m.Wear = "wear"
m.TargetId = "targetId"

return m
