local m = {}

m.ID = "illarion:id"
m.CharacterType = "illarion:characterType"
m.Race = "illarion:race"
m.SkinColor = "illarion:skinColor"
m.HairColor = "illarion:hairColor"
m.Hair = "illarion:hair"
m.Beard = "illarion:beard"
m.MagicType = "illarion:magicType"
m.MagicFlags = "illarion:magicFlags:"
m.Quests = "illarion:quests:"
m.AttributeOffsets = "illarion:attributeOffsets:"
m.BaseAttributes = "illarion:baseAttributes:"
m.TransientBaseAttributes = "illarion:transientBaseAttributes:"
m.PoisonValue = "illarion:poisonValue"
m.MentalCapacity = "illarion:mentalCapacity"
m.Language = "illarion:language"
m.LastSpokenText = "illarion:lastSpokenText"
m.Effects = "illarion:effects"
m.Skills = "illarion:skills:"
m.MinorSkills = "illarion:skills:minor:"
m.CurrentLoginTimestamp = "illarion:currentLoginTimestamp"
m.TotalOnlineTime = "illarion:totalOnlineTime"
m.CurrentAction = "illarion:currentAction"
m.LastActionScript = "illarion:lastActionScript"
m.LastActionFunction = "illarion:lastActionFunction"
m.LastActionArgs = "illarion:lastActionArgs"
m.Introduction = "illarion:introduction"

return m